# Generated by Django 3.1.7 on 2021-03-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('lift_capacity', models.IntegerField()),
                ('location', models.FloatField()),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('passport', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('account', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('unique_token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passport', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mass', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('departure_point', models.FloatField()),
                ('arrival_point', models.FloatField()),
                ('aprox_arrival_time', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.drone')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipient')),
            ],
        ),
        migrations.AddField(
            model_name='drone',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.owner'),
        ),
    ]
